[features]
seeds = false
skip-lint = false

[programs.localnet]
favorites = "Bw9k2iMMNwWiFxv5WPN6FPmA42KWyr7Ds5Qr2NjaTJge"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
